#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    filters:
    - type: io.kroxylicious.proxy.filter.multitenant.MultiTenantTransformationFilter$Contributor
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      devenv1:
        targetCluster:
          bootstrap_servers: my-cluster-kafka-bootstrap:9092
        clusterNetworkAddressConfigProvider:
          type: PortPerBrokerContributor
          config:
            bootstrapAddress: minikube:30192
        logNetwork: false
        logFrames: false
      devenv2:
        targetCluster:
          bootstrap_servers: my-cluster-kafka-bootstrap:9092
        clusterNetworkAddressConfigProvider:
          type: PortPerBrokerContributor
          config:
            bootstrapAddress: minikube:30292
        logNetwork: false
        logFrames: false
